#!/bin/bash

search_macro()
{
    local  __resultarg=$2
    local  __macro_list=`grep -e '\.C' $1 | grep LoadMacro | tr -d " \t\r" | awk -F"\"" '{print $2;}'`

    local  __list=""
    for m in $__macro_list
    do
        __list=$__list" "`eval echo -e "$m"`
    done

    if [[ "$__resultarg" ]]; then
        eval $__resultarg="'$__list'"
    else
        echo "$__list"
    fi
}


start_macro=$1
search_term=$2

macro_list=""

main_list=$(search_macro $start_macro)



#for macro in $main_list
#do
#    file=`eval echo -e "$macro"`
#    search_macro $file list
#    main_list=$main_list" "$list
#done



for m in $main_list
do
  #file_final_list=`eval echo -e "$m"`
  #echo $file_final_list
  echo $m
done

























